services:
    mongodb:
        image: 'mongo'
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - ./mongo-init:/docker-entrypoint-initdb.d:ro
        networks:
            - app-network
        restart: unless-stopped
    gateway-server:
        build: ./gateway-server
        ports:
            - '3000:3000'
        volumes:
            - ./gateway-server:/app
        environment:
            - JWT_SECRET=72e08575afceb25379c414b98f40af84cd574b9beaa8c3509b586098c9b84d2e
        networks:
            - app-network
        depends_on:
            - mongodb
            - auth-server
            - event-server
        env_file:
            - ./gateway-server/.env
        command: ['npm', 'run', 'start:dev']
    auth-server:
        build: ./auth-server
        ports:
            - '3001:3001'
        volumes:
            - ./auth-server:/app
        environment:
            - JWT_SECRET=72e08575afceb25379c414b98f40af84cd574b9beaa8c3509b586098c9b84d2e
        networks:
            - app-network
        depends_on:
            - mongodb
            - event-server
        env_file:
            - ./auth-server/.env
        command: ['npm', 'run', 'start:dev']

    event-server:
        build: ./event-server
        ports:
            - '3002:3002'
        volumes:
            - ./event-server:/app
        environment:
            - JWT_SECRET=72e08575afceb25379c414b98f40af84cd574b9beaa8c3509b586098c9b84d2e
        networks:
            - app-network
        depends_on:
            - mongodb
        env_file:
            - ./event-server/.env
        command: ['npm', 'run', 'start:dev']

volumes:
    mongo_data: {}

networks:
    app-network:
        driver: bridge
